version: '3'

services:
  redis-master:
    container_name: redis-master
    image: redis:3
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis-master:/data"

  redis-slave:
    container_name: redis-slave
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    volumes:
      - "./data/redis-slave:/data"
    links:
      - redis-master

  redis-sentinel:
    container_name: redis-sentinel
    build: redis-sentinel
    links:
      - redis-master
